// <auto-generated />
namespace baitaplon.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.2")]
    public sealed partial class TaoBangAdminVaDoanhThu : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TaoBangAdminVaDoanhThu));
        
        string IMigrationMetadata.Id
        {
            get { return "202606121311287_TaoBangAdminVaDoanhThu"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
